sudo: required
services:
  - docker 

before_install:
  - docker build -t barryduggan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true barryduggan/react-test npm test

after_success:
  - docker build -t barryduggan/multi-client ./client 
  - docker build -t barryduggan/multi-nginx ./nginx
  - docker build -t barryduggan/multi-server ./server
  - docker build -t barryduggan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push barryduggan/multi-client 
  - docker push barryduggan/multi-nginx
  - docker push barryduggan/multi-server
  - docker push barryduggan/multi-worker

